[toolchain]

[features]
seeds = false
skip-lint = false

[workspace]
members = ["programs/earn", "programs/ext_earn"]
exclude = ["programs/portal"]

[programs.localnet]
earn = "MzeRokYa9o1ZikH6XHRiSS5nD8mNjZyHpLCBRTBSY4c"
ext_earn = "wMXX1K1nca5W4pZr1piETe78gcAVVrEFi9f4g46uXko"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "tests/keys/user.json"

[test]
upgradeable = true

[scripts]
test = "pnpm run jest --preset ts-jest --verbose --testPathPattern=tests/unit"
