[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
earn = "Ea18o3BKAQD8p3DTZ1mabgJiRM7XkoYtmh9TWgxFv6gh"
mint-master = "7j9tN2dS7CuPfKPFvhh8HWWNgsPgN7jsDdDiPXMrjemb"
registrar = "DJ3kM7oLuua6NZjnYgCA8SMFhYc1MJMAZ21HmP52ugD1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run jest --preset ts-jest"
