[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
earn = "Ea18o3BKAQD8p3DTZ1mabgJiRM7XkoYtmh9TWgxFv6gh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run jest --preset ts-jest"
