[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
earn = "MzeRokYa9o1ZikH6XHRiSS5nD8mNjZyHpLCBRTBSY4c"
portal = "mZEroYvA3c4od5RhrCHxyVcs2zKsp8DTWWCgScFzXPr"
wrapped-m = "ATPNKbFx7D5bQaKV4YSsoQePsUpkrihHBHLzPKTPeuzL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "tests/keys/user.json"

[scripts]
test = "yarn run jest --preset ts-jest"
