FROM node:20-slim

WORKDIR /app

COPY package.json ./
COPY yarn.lock ./
RUN yarn install

COPY services/yield-bot services/yield-bot
RUN yarn tsc services/yield-bot/main.ts 

CMD ["node", "services/yield-bot/main.js", "distribute"]
