// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";

export class Claim {
  static encode(message: Claim, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.tokenAccount);

    writer.uint32(16);
    writer.uint64(message.amount);
  }

  static decode(reader: Reader, length: i32): Claim {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Claim();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.tokenAccount = reader.string();
          break;

        case 2:
          message.amount = reader.uint64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  tokenAccount: string;
  amount: u64;

  constructor(tokenAccount: string = "", amount: u64 = 0) {
    this.tokenAccount = tokenAccount;
    this.amount = amount;
  }
}
