// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";
import { TokenTransaction } from "./TokenTransaction";

export class TokenTransactions {
  static encode(message: TokenTransactions, writer: Writer): void {
    const transactions = message.transactions;
    for (let i: i32 = 0; i < transactions.length; ++i) {
      writer.uint32(10);
      writer.fork();
      TokenTransaction.encode(transactions[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): TokenTransactions {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new TokenTransactions();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.transactions.push(
            TokenTransaction.decode(reader, reader.uint32())
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  transactions: Array<TokenTransaction>;

  constructor(transactions: Array<TokenTransaction> = []) {
    this.transactions = transactions;
  }
}
