name: test
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

# concurrency configuration to cancel in-progress runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  earn-tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/setup

      - name: Run tests
        run: |
          cd tests
          pnpm run jest --preset ts-jest --verbose tests/unit/earn.test.ts
        shell: bash

  ext-earn-tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/setup

      - name: Run tests
        run: |
          cd tests
          pnpm run jest --preset ts-jest --verbose tests/unit/ext_earn.test.ts
        shell: bash

  portal-tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/setup

      - name: Run tests
        run: |
          cd tests
          pnpm run jest --preset ts-jest --verbose tests/unit/portal.test.ts
        shell: bash

  sdk-tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/setup

      - name: Install Foundry Toolchain
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install SDK Dependencies
        run: cd sdk && pnpm install && cd ..
        shell: bash

      - name: Run SDK tests
        run: make test-sdk
        shell: bash

  yield-bot-tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm i -g pnpm && pnpm install && cd sdk && pnpm install && cd ../services/yield-bot && pnpm install && cd ../..
        shell: bash

      - name: Run yield tests
        run: make test-yield-bot
        shell: bash

  index-bot-tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm i -g pnpm && pnpm install && cd sdk && pnpm install && cd ../services/index-bot && pnpm install && cd ../..
        shell: bash

      - name: Run index tests
        run: make test-index-bot
        shell: bash

  yield-calc-tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/setup

      - name: Run yield calculation tests
        run: make test-yield
        shell: bash
