name: test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  earn-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/setup

      - name: Run tests
        run: yarn run jest --preset ts-jest --verbose tests/unit/earn.test.ts
        shell: bash

  ext-earn-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/setup

      - name: Run tests
        run: yarn run jest --preset ts-jest --verbose tests/unit/ext_earn.test.ts
        shell: bash

  portal-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/setup

      - name: Run tests
        run: yarn run jest --preset ts-jest --verbose tests/unit/portal.test.ts
        shell: bash

  sdk-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/setup

      - name: Install SDK Dependencies
        run: cd sdk && yarn install && cd ..
        shell: bash

      - name: Run SDK tests
        run: make test-sdk
        shell: bash

  yield-bot-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Node Dependencies
        run: npm i -g yarn && yarn install
        shell: bash

      - name: Install SDK Dependencies
        run: cd sdk && yarn install && cd ..
        shell: bash

      - name: Run yield tests
        run: make test-yield-bot
        shell: bash
