name: Devnet Build and Deploy - Portal

on:
  push:
    branches: [main]
    paths:
      - "programs/portal/**"

jobs:
  deploy-portal:
    uses: solana-developers/github-workflows/.github/workflows/reusable-build.yaml@v0.2.5
    with:
      program: "portal"
      network: "devnet"
      deploy: true
      upload_idl: true
      verify: false
      use-squads: false
      priority-fee: "300000"
    secrets:
      DEVNET_SOLANA_DEPLOY_URL: ${{ secrets.DEVNET_SOLANA_DEPLOY_URL }}
      DEVNET_DEPLOYER_KEYPAIR: ${{ secrets.DEVNET_DEPLOYER_KEYPAIR }}
      PROGRAM_ADDRESS_KEYPAIR: ${{ secrets.PROGRAM_ADDRESS_KEYPAIR_PORTAL }}